verbose: false
go:
  cgo: false
  version: 1.15
repository:
  path: github.com/bosh-prometheus/cf_exporter
build:
  flags: -mod=vendor -a -tags 'netgo static_build'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - NOTICE
crossbuild:
  platforms:
    - darwin/amd64
    - linux/386
    - linux/amd64
    - linux/arm
    - linux/arm64
    - linux/ppc64
    - linux/ppc64le
    - windows/386
    - windows/amd64
