sudo: required

language: go

go:
  - 1.15.x

go_import_path: github.com/bosh-prometheus/cf_exporter

services:
  - docker


jobs:
  include:
    - stage: Run tests
      script: make test

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=boshprometheus/cf-exporter
        - secure: mKWGE1/len9O5n5qtR3tJ2w7sWGVpV+6W46qQKt1u1cI5BiNKe/wfIhBz52OWYFVK1ZDs3qqU5Nb187vJscIB1VETZ4gNKRYA21+iplo/cctcmN0C2oKjp7iVkVyhJdd0ywM9c/yafN2DHmWmECQ+W4OXDbkXdYE6z4i65u1dIb7JlYvlmmQWZBgdnCqjONp6gDFD3ZAWVEsVmbLhHzA2peKzNmsSvlUNYnJXy/ZOOk//u4IIUUXLxQXnMi6z9O9QcDgeqbwexSc4WTiE28Bau8ZjhUwPpFNhygLUvIfx3ZkO/2jW+zXHxbcAxFg1FNwObufdhJd8GSjhbmnejxSywIL4uJg3Lmb5567YZio+znGeS7M9CSXKPx5LWSSSrbvGebuM1BDP8beWUEaI2bVgw/JFoMSVh1JZ8tijXqSCmQKSy/kJI6lU61/momk5dQ81cEdTzrMuJW5Q8+Q2StPvw2r0QGwjPfEtCWyHsguxWFwZZ7enbJDCsrAaOzeQ9cLk70xPE4dwANlhPrL+KDWtftztv/HFd8wN86mEEoZszOX3aMPDQeCxN1K77VXCkMT9npao+8bEyfZ+c1QyyJ2upGt0faqG7p07OvoIOEe60dP8L7m8mlxQjeh2I+4iSdrwy6zsMKtC7SxUQaLCzI5X+qSzL4AmjCvEFaSIRq7BkE=
        - secure: zXuv55q00m6wsI/NTJnQ+zyg1teYRGeT0xLT3xO7wjP5YbDSxx9DaCK4DG7bWM9a44OwrBhzy+f0oGHfO+PWjGnIhn8+f7o3PNSF5L1LMxcYrKhV8JKQ1nj3F7zrXui0kS2OZTX4hreg3w9r0ctC6iK5k8CSAviffyzTreF13qbHJBASegIpbh2RkXROVPG5b4zX/5mrEZVGh5hBqrKlwotxoPqYGe/1BoSxiUfgFPdR71tp2tipp+Vk0fpSllVnfsgKhkAl26Gxf5cMAq+gzQA0q4CgSOCYhQrsfkH7pBwIvAIPk+3WsKUPeADl78vdCzLW/UEcLG7Yuw+yb9RI0+scBrn09Bgn4eHeTnUlX5uer3vKFVfftek+Bsdx9thgNIAn/chzkls5OyLWdXzdiheJuybeMVquSBnmnKNkNqZTGH0wHF3T8xND+h6EgG/ZT1CKulTb0Zl+ybs6nSxhGwoQioHXLzqpiN3QY8Ho1BSqFnbt7urZ6VPRrkJ2GNSrBj2FP6OwrmiS95e0iZsZ+97YNzEGmFU+8G+VkaGqXiZn/l9GhaN3V5EnZF5rmxfbW0zinZdHP52yXKVQfkKnesIvbG1WBHrlDzgq62ybjjZ8KIoaxe5orihubcp82aIU//N0RFaBemwCOMT6nbYHa+yv1rkEJZE69MIE7b9HJZs=
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/cf_exporter cf_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
